infra:
    log_dir: /data2/dri/hidisc/hidisc/exps # where all the experiments are
    exp_name: Exp001 # use the same name as the training experiment
    comment: patient_disc_dev # can use this to customize for each experiment
    seed: 1000
model:
    backbone: resnet50
    mlp_hidden: []
    num_embedding_out: 128
data:
    db_root:  /data1/dri/hidisc/hidisc/datasets/opensrh
    backbone: resnet50
    mlp_hidden: []
    num_embedding_out: 128
    train_alg: hidisc
eval:
    predict_batch_size: 128
    knn_batch_size: 1024
    ckpt_dir : 1f1aea1b-Oct15-15-42-41-patient_disc_dev_/models
    