infra:
    log_dir: /data1/dri/hidisc/hidisc/exps # where all the experiments are
    exp_name: Exp002 # use the same name as the training experiment
    comment: patient_disc_dev # can use this to customize for each experiment
    seed: 1000
model:
    backbone: RN50
    mlp_hidden: []
    num_embedding_out: 7
    templates: ["a histopathology slide showing {c}",
            "histopathology image of {c}",
            "pathology tissue showing {c}",
            "presence of {c} tissue on image"]
data:
    db_root:  /data1/dri/hidisc/hidisc/datasets/opensrh
    data_classes : { 'hgg' : 'high grade glioma', 'lgg' : 'low grade glioma', 'mening' : 'meningioma','metast' : 'metastatic tumor', 'normal' : 'normal brain tissue', 'pituita' : 'pituitary adenoma', 
           'schwan' : 'schwannoma'}
    backbone: RN50
    mlp_hidden: []
    num_embedding_out: 7
    train_alg: hidisc
eval:
    # predict_batch_size: 128
    predict_batch_size: 128
    # knn_batch_size: 1024
    knn_batch_size: 1024

    #HiDisc-Slide + strong augs
    ckpt_dir : b316b58d-Oct18-22-59-32-patient_disc_dev_/models
    