infra:
    log_dir: /data1/dri/hidisc/hidisc/exps # where all the experiments are
    exp_name: Exp001 # use the same name as the training experiment
    comment: patient_disc_dev # can use this to customize for each experiment
    seed: 2000
model:
    backbone: resnet50
    mlp_hidden: []
    num_embedding_out: 128
data:
    db_root:  /data1/dri/hidisc/hidisc/datasets/opensrh
    backbone: resnet50
    mlp_hidden: []
    num_embedding_out: 128
    train_alg: hidisc
eval:
    # predict_batch_size: 128
    predict_batch_size: 128
    # knn_batch_size: 1024
    knn_batch_size: 1024

    #HiDiSC-Patient + strong augs
    # ckpt_path: 07ec1397-Aug04-08-35-45-patient_disc_dev_/models/ckpt-epoch22399.ckpt # eg. hash_datetime_expname_comment/models/ckpt-epochXX-accXXX.ckpt
    
    #HiDiSC-Patch + strong augs
    #ckpt_path: be74064f-Sep19-02-16-33-patch_disc_dev_/models/ckpt-epoch7599.ckpt
    # ckpt_path : 00c2816f-Sep22-15-50-58-patch_disc_dev_/models/ckpt-epoch23999.ckpt

    #HiDiSC-Slide + strong augs
    # ckpt_path: 6edee2ae-Sep21-14-17-42-patch_disc_weak_/models/ckpt-epoch5599.ckpt
    
    #HiDisc-Patch + weak augs
    #ckpt_path : a18e83b8-Sep23-14-53-05-patch_disc_weak_/models/ckpt-epoch23999.ckpt

    #HiDisc-Patient + weak augs
    #ckpt_path : b5f3baa8-Sep23-22-38-25-patient_disc_weak_/models/ckpt-epoch23999.ckpt

    #HiDisc-Slide + weak augs
    # ckpt_path : f93d0124-Sep25-00-40-13-slide_disc_weak_/models/ckpt-epoch23999.ckpt
    
    #HiDisc-Slide + strong augs
    ckpt_path : 1f1aea1b-Oct15-15-42-41-patient_disc_dev_/models/ckpt-epoch15599.ckpt
    