infra:
    log_dir: /data1/dri/hidisc/hidisc/exps/Exp018 # where all the experiments are
    exp_name: a # create a subdirectory for each set of experiments
    comment: patient_disc_dev # can use this to customize for each experiment
    seed: 1000
data:
    db_root: /data1/dri/hidisc/hidisc/datasets/opensrh
    data_classes : {"Cellularity","Nuclear Pleomorphism","Vascularity","Tissue Architecture","Necrosis","Cell Infiltration",
    "Inflammatory Response","Molecular Markers","Lipid Content","Protein Density","Nucleic Acid Presence","Cellular Morphology",
    "Chemical Composition","Microcalcifications","Cytoplasmic Inclusions","Stromal Components","Mitotic Figures","Myelin Content"}
    # train_augmentation:
    #     - which: random_horiz_flip
    #       params: {}
    #     - which: random_vert_flip
    #       params: {}
    #     - which: gaussian_noise
    #       params: {}
    #     - which: color_jitter
    #       params: {}
    #     - which: random_autocontrast
    #       params: {}
    #     - which: random_solarize
    #       params:
    #         threshold: 0.2
    #     - which: random_sharpness
    #       params:
    #         sharpness_factor: 2
    #     - which: gaussian_blur
    #       params:
    #         kernel_size: 5
    #         sigma: 1
    #     - which: random_affine
    #       params:
    #         degrees: 10
    #         translate: [0.1, 0.3]
    #     - which: random_resized_crop
    #       params:
    #         size: 224
    #     - which: random_erasing
    #       params: {}
    # valid_augmentation:
    #     - which: random_horiz_flip
    #       params: {}
    #     - which: random_vert_flip
    #       params: {}
    #     - which: gaussian_noise
    #       params: {}
    #     - which: color_jitter
    #       params: {}
    #     - which: random_autocontrast
    #       params: {}
    #     - which: random_solarize
    #       params:
    #         threshold: 0.2
    #     - which: random_sharpness
    #       params:
    #         sharpness_factor: 2
    #     - which: gaussian_blur
    #       params:
    #         kernel_size: 5
    #         sigma: 1
    #     - which: random_affine
    #       params:
    #         degrees: 10
    #         translate: [0.1, 0.3]
    #     - which: random_resized_crop
    #       params:
    #         size: 224
    #     - which: random_erasing
    #       params: {}
    # rand_aug_prob: 0.3
    train_augmentation: {}
    valid_augmentation: {}
    hidisc:
        num_slide_samples: 2
        num_patch_samples: 2
        num_transforms: 1
    balance_study_per_class: true
model:
    backbone: resnet50
    mlp_hidden: []
    num_embedding_out: 128

training:
    objective:
        which: hidisc
        params:
            lambda_patient: 1.0
            lambda_slide: 1.0
            lambda_patch: 1.0
            supcon_params:
                temperature: 0.07
                base_temperature: 0.07
                contrast_mode: all
    # batch_size: 10
    batch_size: 32
    num_epochs: 40000
    optimizer: adamw # [sgd, adam, adamw]
    learn_rate: 1.0e-3
    scheduler:
        which: cos_warmup
        params:
            num_warmup_steps: 0.1
            num_cycles: 0.5
    imagenet_backbone_checkpoint: null
    # eval_ckpt_ep_freq: 400
    eval_ckpt_ep_freq: 400
